### ISSUE TITLE
Very concerning xss security issue with crowdin translation.

### ISSUE THREAD

**Issue by LualtOfficial** [KosmX/emotes-open-collection#32]
While i was translating english to dutch i found that there are html tags within the translation, this means that people could XSS via this, please change this because it can put alot of users in danger!

along side making it that you dont have html tags in the translations please also make sure to sanitize whatever is going through

**Comment by KosmX** [comment]
Thanks for noticing, and I'll fix that page..  
But translations are only semi-automate, I'll have to confirm in a form of a Pull Request.  
Also, when discovering security vulnerabilities, try to contact the developers without opening an issue, so devs has time to react before going public. (I believe Security tab is used for that)

**Comment by LualtOfficial** [comment]
ah thats was a mistake on my part i should have known that, but its good knowing theres atleast some defense before translations go into the actual project
